root = "."
tmp_dir = "dist/bin"

[build]
bin = "./dist/bin/gin-starter"
cmd = "go build -ldflags=\"-s -w\" -o ./dist/bin/gin-starter ./cmd/cli/main.go"
delay = 1000
exclude_dir = ["deploy", "dist", "script", "test"]
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
full_bin = "./dist/bin/gin-starter"
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
