basic:
  system:
    debug_mode: false
    server_address: :7086
    enable_cors: true
    enable_auth: true
    external_svr_address: http://localhost:7086/
    trusted_proxies: 127.0.0.1;10.0.0.0/8
    static_dir: ./static
    static_url: /static
  log:
    log_file_name: log/gin-starter-%s.log
    log_file_name_format: 20060102
    default_level: -4
  database:
    # dbtype: mysql
    # dbhost: 127.0.0.1
    # dbname: temp
    # dbport: 3306
    # dbuser: user
    # dbpassword: password
    dbtype: sqlite3
    dbname: log/app.db
  redis:
    size: 10
    network: tcp
    address: localhost:6379
    password:
    db: 0
    key_pairs:
    default_expiration: 10m
    enable_redis_cache: true
    enable_redis_session: true
    session_name: ssession
  sentry:
    sentry_dsn:
    traces_sample_rate: 1.0
    default_level: -4
