basic:
  system:
    debug_mode: false
    server_address: :7086
    external_svr_address: http://localhost:7086/
    trusted_proxies: 127.0.0.1;10.0.0.0/8
    static_dir: ./static
    static_url: /static
  middlewares:
    log:
      time_format : 2006-01-02T15:04:05Z07:00
      utc : false
      skip_paths:
      default_level : 0
    cors:
      enable: true
      allow_methods:
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
        - OPTIONS
      allow_headers:
        - Origin
        - Content-Length
        - Content-Type
      allow_credentials: false
      # max_age: 43200000000000
    session:
      enable: true
      name: x-ssession
      use_redis: true
    static:
      enable: true
      static_dir: ./static
      static_url: /static
      indexes: true
    auth:
      enable: true
      model_file: ./config/model.yaml
      table_name: auth_rules
  database:
    # dbtype: mysql
    # dbhost: 127.0.0.1
    # dbname: temp
    # dbport: 3306
    # dbuser: user
    # dbpassword: password
    dbtype: sqlite3
    dbname: log/gin-stater.db
  redis:
    size: 10
    network: tcp
    address: 127.0.0.1:6379
    password:
    db: 0
    key_pairs:
    default_expiration: 10m
    enable_redis_cache: true
  sentry:
    sentry_dsn:
    traces_sample_rate: 1.0
    default_level: -4
