// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dbo

import (
	"context"
)

type Querier interface {
	GetRoleNamesByUsername(ctx context.Context, username string) ([]*string, error)
	GetValidUserInfo(ctx context.Context, username string, password string) (AuthUser, error)
	VerifyUserCredentials(ctx context.Context, username string, password string) (int64, error)
}

var _ Querier = (*Queries)(nil)
