version: "2"
sql:
  - engine: "sqlite"
    schema: "01_schema.sql"
    queries: "02_query.sql"
    database:
      uri: file:log/gin-stater.db
    rules:
      - sqlc/db-prepare
    gen:
      go:
        package: "dbo"
        out: "../pkg/internal/dbo"
        sql_package: "jmoiron/sqlx"
        emit_interface: true
        emit_json_tags: true
        emit_pointers_for_null_types: true
        query_parameter_limit: 5
